services:
  dirtyworksjazz.dev:
    init: true
    volumes:
      - .:/workspace:cached
      # Use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      - /var/run/docker.sock:/var/run/docker.sock
      
    command: /bin/sh -c "while sleep 1000; do :; done"

